<?php

namespace ContainerPZ1xqIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SmO90Z7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SmO90Z7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SmO90Z7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ArtistController::delete' => ['privates', '.service_locator.sl9TaJ7', 'get_ServiceLocator_Sl9TaJ7Service', true],
            'App\\Controller\\ArtistController::edit' => ['privates', '.service_locator.sl9TaJ7', 'get_ServiceLocator_Sl9TaJ7Service', true],
            'App\\Controller\\ArtistController::index' => ['privates', '.service_locator.Y0zyazV', 'get_ServiceLocator_Y0zyazVService', true],
            'App\\Controller\\ArtistController::new' => ['privates', '.service_locator.h1Klj3y', 'get_ServiceLocator_H1Klj3yService', true],
            'App\\Controller\\ArtistController::show' => ['privates', '.service_locator.V2hzYOu', 'get_ServiceLocator_V2hzYOuService', true],
            'App\\Controller\\DiscController::delete' => ['privates', '.service_locator..8gVxOn', 'get_ServiceLocator__8gVxOnService', true],
            'App\\Controller\\DiscController::edit' => ['privates', '.service_locator..8gVxOn', 'get_ServiceLocator__8gVxOnService', true],
            'App\\Controller\\DiscController::index' => ['privates', '.service_locator.se2q2eP', 'get_ServiceLocator_Se2q2ePService', true],
            'App\\Controller\\DiscController::new' => ['privates', '.service_locator.se2q2eP', 'get_ServiceLocator_Se2q2ePService', true],
            'App\\Controller\\DiscController::show' => ['privates', '.service_locator.bag5iF4', 'get_ServiceLocator_Bag5iF4Service', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.q2ji3lu', 'get_ServiceLocator_Q2ji3luService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.IoQgdHi', 'get_ServiceLocator_IoQgdHiService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\ArtistController:delete' => ['privates', '.service_locator.sl9TaJ7', 'get_ServiceLocator_Sl9TaJ7Service', true],
            'App\\Controller\\ArtistController:edit' => ['privates', '.service_locator.sl9TaJ7', 'get_ServiceLocator_Sl9TaJ7Service', true],
            'App\\Controller\\ArtistController:index' => ['privates', '.service_locator.Y0zyazV', 'get_ServiceLocator_Y0zyazVService', true],
            'App\\Controller\\ArtistController:new' => ['privates', '.service_locator.h1Klj3y', 'get_ServiceLocator_H1Klj3yService', true],
            'App\\Controller\\ArtistController:show' => ['privates', '.service_locator.V2hzYOu', 'get_ServiceLocator_V2hzYOuService', true],
            'App\\Controller\\DiscController:delete' => ['privates', '.service_locator..8gVxOn', 'get_ServiceLocator__8gVxOnService', true],
            'App\\Controller\\DiscController:edit' => ['privates', '.service_locator..8gVxOn', 'get_ServiceLocator__8gVxOnService', true],
            'App\\Controller\\DiscController:index' => ['privates', '.service_locator.se2q2eP', 'get_ServiceLocator_Se2q2ePService', true],
            'App\\Controller\\DiscController:new' => ['privates', '.service_locator.se2q2eP', 'get_ServiceLocator_Se2q2ePService', true],
            'App\\Controller\\DiscController:show' => ['privates', '.service_locator.bag5iF4', 'get_ServiceLocator_Bag5iF4Service', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.q2ji3lu', 'get_ServiceLocator_Q2ji3luService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.IoQgdHi', 'get_ServiceLocator_IoQgdHiService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\ArtistController::delete' => '?',
            'App\\Controller\\ArtistController::edit' => '?',
            'App\\Controller\\ArtistController::index' => '?',
            'App\\Controller\\ArtistController::new' => '?',
            'App\\Controller\\ArtistController::show' => '?',
            'App\\Controller\\DiscController::delete' => '?',
            'App\\Controller\\DiscController::edit' => '?',
            'App\\Controller\\DiscController::index' => '?',
            'App\\Controller\\DiscController::new' => '?',
            'App\\Controller\\DiscController::show' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ArtistController:delete' => '?',
            'App\\Controller\\ArtistController:edit' => '?',
            'App\\Controller\\ArtistController:index' => '?',
            'App\\Controller\\ArtistController:new' => '?',
            'App\\Controller\\ArtistController:show' => '?',
            'App\\Controller\\DiscController:delete' => '?',
            'App\\Controller\\DiscController:edit' => '?',
            'App\\Controller\\DiscController:index' => '?',
            'App\\Controller\\DiscController:new' => '?',
            'App\\Controller\\DiscController:show' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
