<?php

namespace ContainerPxZwTEo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArtistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.V2hzYOu.App\Entity\Artist' shared service.
     *
     * @return \App\Entity\Artist
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.V2hzYOu": it references class "App\\Entity\\Artist" but no such service exists.');
    }
}
