<?php

namespace ContainerPxZwTEo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchDiscTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SearchDiscType' shared autowired service.
     *
     * @return \App\Form\SearchDiscType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SearchDiscType.php';

        return $container->privates['App\\Form\\SearchDiscType'] = new \App\Form\SearchDiscType();
    }
}
