<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5tkxg01\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5tkxg01/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5tkxg01.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5tkxg01\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5tkxg01\App_KernelDevDebugContainer([
    'container.build_hash' => '5tkxg01',
    'container.build_id' => 'ae3f5baa',
    'container.build_time' => 1654856573,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5tkxg01');
