<?php

namespace ContainerPxZwTEo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V2hzYOuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V2hzYOu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V2hzYOu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'artist' => ['privates', '.errored..service_locator.V2hzYOu.App\\Entity\\Artist', NULL, 'Cannot autowire service ".service_locator.V2hzYOu": it references class "App\\Entity\\Artist" but no such service exists.'],
        ], [
            'artist' => 'App\\Entity\\Artist',
        ]);
    }
}
